export { AboutComponent as About } from './about'
export { TechComponent as Tech } from './tech'
export { EduComponent as Edu } from './edu'
export { LinksComponent as Links } from './links'
export { ContactComponent as Contact } from './contact'